# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["**/*.plist", "**/Contents.json", "**/*.entitlements", "**/*.pbxproj", "**/*.xcworkspacedata", "**/*.xcscheme", "**/swiftpm/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Shota FUJI <pockawoooh@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
