# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "*.sql"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Shota FUJI <pockawoooh@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
